ARG version
FROM almalinux:${version:-9}
ARG course="Devops with AWS" \
    trainer="siva kumar reddy" \
    duartion="120 hrs"
ENV duration=$duartion
RUN echo "Course : $course, duartion is $duartion"
CMD ["sleep", "100"]